"""update table

Revision ID: eb72abd76e88
Revises: b9f74c0bc0fe
Create Date: 2024-04-03 14:05:27.613715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb72abd76e88"
down_revision: Union[str, None] = "b9f74c0bc0fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pattern_preset_category",
        sa.Column("id", sa.Integer(), nullable=False, comment="纹理类别ID"),
        sa.Column("name", sa.String(length=128), nullable=False, comment="纹理类别"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pattern_preset_category_id"),
        "pattern_preset_category",
        ["id"],
        unique=False,
    )
    op.add_column(
        "pattern_preset", sa.Column("category_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "pattern_preset", "pattern_preset_category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pattern_preset", type_="foreignkey")
    op.drop_column("pattern_preset", "category_id")
    op.drop_index(
        op.f("ix_pattern_preset_category_id"), table_name="pattern_preset_category"
    )
    op.drop_table("pattern_preset_category")
    # ### end Alembic commands ###
